# Feit OM60/RGBW/CA/AG 
# https://www.menards.com/main/electrical/alarms-security-systems/security-accessories/feit-electric-reg-60w-equivalent-a19-color-changing-and-tunable-white-led-light-bulb/a800rgbwag/p-1531290477098-c-6464.htm
# $12.99 
# 800 lumen

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  
<<: !include base.yaml

power_supply:
  - id: rgb_power
    pin: GPIO13

output:
  - platform: esp8266_pwm
    id: output_component1
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_component2
    pin: GPIO12

light:
  - platform: cwww
    name: ${friendly_name}
    id: ${device_name}
    cold_white: output_component1
    warm_white: output_component2
    cold_white_color_temperature: 153 mireds
    warm_white_color_temperature: 500 mireds
    restore_mode: ALWAYS_ON
  - platform: fastled_spi
    id: ${device_name}_rgb
    name: "${friendly_name} RGB"
    chipset: SM16716
    clock_pin: GPIO4
    data_pin: GPIO14
    power_supply: rgb_power
    num_leds: 8
    rgb_order: BGR
    restore_mode: ALWAYS_OFF

