binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button 1"
    internal: true
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button 2"
    internal: true
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button 3"
    internal: true
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button 4"
    internal: true
  - platform: status
    name: "${friendly_name} Status"
    

switch:
  - platform: gpio
    name: "${relay1_name}"
    id: relay_1
    pin: GPIO12
    restore_mode: ${relay1_restoremode}
  - platform: gpio
    name: "${relay2_name}"
    id: relay_2
    pin: GPIO5
    restore_mode: ${relay2_restoremode}
  - platform: gpio
    name: "${relay3_name}"
    id: relay_3
    pin: GPIO4
    restore_mode: ${relay3_restoremode}
  - platform: gpio
    name: "${relay4_name}"
    id: relay_4
    pin: GPIO15
    restore_mode: ${relay4_restoremode}

status_led:
  pin:
    number: GPIO13
    inverted: yes

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

# Base Household Config
<<: !include base.yaml
