esphome:
  name: mpv2rq_sw1
  platform: ESP8266
  board: esp01_1m

<<: !include include/wifi.yaml

api:

logger:

ota:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "Plug Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Plug Relay"
    pin: GPIO15
    id: relay

status_led:
  pin:
    number: GPIO0
    inverted: yes

